[build-system]
requires = ["setuptools>=77", "packaging>=24.2", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "eftcamb"
authors = [
    { name = "EFTCAMB developers" },
    { name = "Antony Lewis" },
]
description = "EFTCAMB: Effective Field Theory for CAMB — a modified-gravity extension"
keywords = ['cosmology', 'CAMB', 'CMB', 'EFTCAMB', 'modified gravity']
readme = "docs/README_pypi.rst"
license = "LicenseRef-GPLv3-arxiv"
license-files = ["LICENCE.txt"]
dynamic = ["version"]
requires-python = ">=3.10.0"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Operating System :: OS Independent",
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Astronomy",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "numpy>=1.22", "scipy>=1.0", "sympy>=1.0", "packaging>=24.2"
]

[project.optional-dependencies]
docs = ["sphinx>=4.0", "sphinx_rtd_theme>=1.0", "sphinxcontrib-jquery", "sphinx_markdown_builder", "jupytext"]
dev = ["ruff>=0.11.0", "pre-commit>=3.0.0"]

[project.scripts]
eftcamb = "eftcamb._command_line:run_command_line"

[project.urls]
Homepage = "https://eftcamb.github.io"
Source = "https://github.com/LinSJ-astronomy/EFTCAMB-MSJ"
Tracker = "https://github.com/LinSJ-astronomy/EFTCAMB-MSJ/issues"
Licensing = "https://github.com/LinSJ-astronomy/EFTCAMB-MSJ/blob/eftcamb/LICENCE.txt"

[tool.setuptools.dynamic]
version = { attr = "eftcamb.__version__" }

[tool.ruff]
line-length = 120
target-version = "py310"

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.lint.per-file-ignores]
"eftcamb/__init__.py" = ["F401", "E402"]
"eftcamb/emission_angle.py" = ["E741"]
"fortran/tests/CAMB_test_files.py" = ["E731"]
"**/*.ipynb" = ["F405", "E501", "F403", "E402"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
skip-magic-trailing-comma = false
docstring-code-format = true

[tool.flake8]
select = [
    "E713", "E704", "E703", "E714", "E741", "E10", "E11", "E20", "E22", "E23", "E25", "E27",
    "E301", "E302", "E304", "E9", "F405", "F406", "F5", "F6", "F7", "F8", "W1", "W2", "W3", "W6"
]
